const PREFIX='baton-4bed121e-';
const CACHE=PREFIX+'c7a59d796fce';
const SHELL=["/Meisters-Baton/","/Meisters-Baton/index.html","/Meisters-Baton/icon.svg","/Meisters-Baton/manifest.webmanifest","/Meisters-Baton/third-party-notices.txt","/Meisters-Baton/icons/icon-192.png","/Meisters-Baton/icons/icon-512.png","/Meisters-Baton/assets/AtlasModel--ZyIlHjm.js","/Meisters-Baton/assets/AtlasModel-DkqGD3YW.css","/Meisters-Baton/assets/BookReader-98NGeQyj.css","/Meisters-Baton/assets/BookReader-BwATSEPi.js","/Meisters-Baton/assets/GrowiWiki-D9AQnXjk.js","/Meisters-Baton/assets/GrowiWiki-DQ8lD0f6.css","/Meisters-Baton/assets/WikiAtlas-DsX9g9lM.js","/Meisters-Baton/assets/WikiAtlas-ZFcISQJk.css","/Meisters-Baton/assets/WikiMedia-CDYRgVPI.js","/Meisters-Baton/assets/esm-BRHRw47d.js","/Meisters-Baton/assets/esm-DIKZeFbi.js","/Meisters-Baton/assets/index-BsBEWGrP.css","/Meisters-Baton/assets/index-DkUQmRGU.js","/Meisters-Baton/assets/web-CG5KeJWT.js","/Meisters-Baton/assets/web-DlAE4hKr.js"];
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(SHELL))));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith(PREFIX)&&key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{
 const request=event.request,url=new URL(request.url);
 if(request.method!=='GET'||url.origin!==self.location.origin||url.pathname.startsWith('/api/'))return;
 if(request.mode==='navigate') {event.respondWith(fetch(request).then(response=>{if(response.ok){const copy=response.clone();caches.open(CACHE).then(cache=>cache.put('/Meisters-Baton/index.html',copy));}return response;}).catch(()=>caches.match('/Meisters-Baton/index.html')));return;}
 if(url.pathname.startsWith('/Meisters-Baton/assets/')||url.pathname.startsWith('/Meisters-Baton/icons/')||url.pathname==='/Meisters-Baton/icon.svg'||url.pathname==='/Meisters-Baton/third-party-notices.txt')event.respondWith(caches.match(request).then(hit=>hit||fetch(request).then(response=>{if(response.ok){const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(request,copy));}return response;})));
});
