/**
 * Plain-language reading aids, not manufacturing specifications.
 * General definitions and the 26th-generation team's particular names are kept distinct.
 * Match longer terms first. One-character terms (型 / 桁) belong in explicit links or
 * the glossary index; do not highlight them as unrestricted substrings in prose.
 */
export interface BookTerm {
  id: string;
  term: string;
  reading?: string;
  aliases: string[];
  short: string;
  description: string;
  contrast?: string;
  chapter: string;
  source: string;
  sourceUrl?: string;
}

const WING_GEOMETRY = 'https://www1.grc.nasa.gov/beginners-guide-to-aeronautics/wing-geometry/';
const CARBON_TERMS = 'https://www.toraycma.com/resources/carbon-fiber-terminology/';
const VACUUM_MATERIALS = 'https://www.westsystem.com/product-categories/vacuum-bagging-supplies/';
const EPOXY = 'https://www.westsystem.com/product-categories/epoxy-resins-hardeners/';
const MOLD_GUIDE =
  'https://www.fibreglast.com/blogs/learning-center/mold-plug-construction-for-composites-complete-guide';
const RECORD = 'https://discord.com/channels/1384740821034729567/';

export const BOOK_GLOSSARY: BookTerm[] = [
  {
    id: 'mold',
    term: '型',
    reading: 'かた',
    aliases: [],
    chapter: 'mold',
    short: '材料に、つくりたい部品の形を写すための道具。',
    description:
      '同じ曲面をつくれるよう、材料を当てる面の形をあらかじめ整えた道具です。この本では、ふくらんだ原形をつくり、その面を写したくぼみ側の型で外皮をつくります。',
    contrast: '型は形を写す道具。治具は、作業中の部品の位置や向きを保つ道具です。',
    source: '一般原理：Fibre Glast 型製作ガイド／26代の型工程',
    sourceUrl: MOLD_GUIDE,
  },
  {
    id: 'male-mold',
    term: '凸型',
    reading: 'とつがた',
    aliases: ['雄型'],
    chapter: 'mold',
    short: '部品の曲面を、ふくらんだ側で表した原形。',
    description:
      'この本では、並べた板の間を埋めてつくる、ふくらんだ形の原形を指します。その表面に材料を重ねて固め、取り外すことで凹型をつくります。',
    contrast: '凸型の面を写して凹型をつくり、凹型で外皮をつくる、という順序です。',
    source: '一般原理：Fibre Glast 型製作ガイド／26代の型工程',
    sourceUrl: MOLD_GUIDE,
  },
  {
    id: 'female-mold',
    term: '凹型',
    reading: 'おうがた',
    aliases: ['雌型'],
    chapter: 'mold',
    short: '内側のくぼみに材料を沿わせて成形する型。',
    description:
      'つくりたい部品の外側の形を、内側のくぼみとして持つ型です。この本では、凸型から写し取った面へ布状の材料を重ね、外皮をつくります。',
    contrast: '外皮は完成品に残る部品ですが、凹型は外皮を取り出した後に残る道具です。',
    source: '一般原理：Fibre Glast 型製作ガイド／26代の型工程',
    sourceUrl: MOLD_GUIDE,
  },
  {
    id: 'cross-section',
    term: '断面',
    reading: 'だんめん',
    aliases: ['断面形状'],
    chapter: 'overview',
    short: '物をある位置で切ったと考えたときの面の形。',
    description:
      '長い物の途中を輪切りにしたと想像すると、切り口の形が見えてきます。プロペラは位置によってその形が変わるため、どこで切った断面なのかも一緒に読みます。',
    contrast: '上から見た輪郭と、途中を切って見た断面は別の図です。',
    source: '一般原理：NASA Wing Geometry',
    sourceUrl: WING_GEOMETRY,
  },
  {
    id: 'section-plate',
    term: '断面板',
    reading: 'だんめんばん',
    aliases: ['ステンレス断面板'],
    chapter: 'mold',
    short: '決められた位置の断面形状を縁に持つ板。',
    description:
      '型の曲面を決めるために、形の異なる板を決められた位置へ並べます。26代の本番型ではステンレス板の上端を基準に、その間の面を整えています。',
    contrast: '型の断面板と、完成したブレードの内部に残す桁リブは別の部品です。',
    source: '26代記録：2025年12月1日 本番型',
    sourceUrl: RECORD + '1391736630737633290/1445269288368869376',
  },
  {
    id: 'datum-surface',
    term: '基準面',
    reading: 'きじゅんめん',
    aliases: [],
    chapter: 'mold',
    short: '位置や高さを比べるときに、よりどころにする面。',
    description:
      '形を整えるときに「ここに合わせる」と決めておく面です。この本の型工程では、断面板の上端が示す形をよりどころに、板の間の高さを比べます。',
    contrast: '今ある下地の面を、そのまま正しい形の基準にするわけではありません。',
    source: '26代記録：2025年12月1日 本番型をもとに編集',
    sourceUrl: RECORD + '1391736630737633290/1445269288368869376',
  },
  {
    id: 'putty',
    term: 'パテ',
    aliases: [],
    chapter: 'mold',
    short: 'くぼみや隙間に盛り、形を整えるための材料。',
    description:
      '粘土のように盛って使う材料の総称で、固まった後に形を整える用途があります。この本では、型の板と板の間を埋める場面などに登場しますが、場所ごとに使用製品を確かめます。',
    contrast: '「パテ」は用途や形状の呼び名で、すべてがエポキシ系とは限りません。',
    source: '26代記録：2025年12月11日 パテの割れと補修',
    sourceUrl: RECORD + '1391736630737633290/1448830631751581766',
  },
  {
    id: 'sanding-block',
    term: '当て板',
    reading: 'あていた',
    aliases: ['やすり棒'],
    chapter: 'mold',
    short: 'やすりの裏を支え、面に当てる形を保つ道具。',
    description:
      '紙やすりなどを取り付け、手で持って動かすための板や棒です。教材写真では、握る側と削る側を分けて見ます。',
    contrast: '当て板は道具、断面板は型の形を決める基準です。',
    source: '26代記録：2026年1月5日 やすり棒の写真',
    sourceUrl: RECORD + '1391736630737633290/1457808620543545379',
  },
  {
    id: 'sanding',
    term: '研磨',
    reading: 'けんま',
    aliases: ['やすりがけ'],
    chapter: 'mold',
    short: '細かな粒で表面を削り、形や粗さを整える作業。',
    description:
      'やすりなどの表面にある硬い粒を動かして、材料を少しずつ取り除きます。この本では、基準として残す場所と、削って整える場所を見分けてから動作を読みます。',
    contrast: '光沢を出すことだけが目的ではなく、型の曲面を整える研磨もあります。',
    source: '26代記録：2025年9月25日 練習型の研磨説明',
    sourceUrl: RECORD + '1391736924246376448/1420786120567816202',
  },
  {
    id: 'grit',
    term: '番手',
    reading: 'ばんて',
    aliases: ['粒度'],
    chapter: 'mold',
    short: 'やすりの粒の粗さを表す、番号による目安。',
    description:
      '同じ表示規格では、一般に数字が大きいほど粒が細かくなります。この本の写真にある番号は道具を見分ける手がかりで、どの場所にも同じ番号を使う指示ではありません。',
    contrast: '番手は削る回数や押し付ける力を表す数字ではありません。',
    source: '一般原理：3M 研磨材案内／26代やすり棒の記録',
    sourceUrl:
      'https://www.3m.co.uk/3M/en_GB/collision-repair-uk/car-repair-and-refinish-processes/abrasive-productivity/',
  },
  {
    id: 'surfacer',
    term: 'サーフェーサー',
    aliases: ['サフェーサー'],
    chapter: 'mold',
    short: '面の細かな粗さを整えるための下地塗料。',
    description:
      '塗装などの前に表面を整えるために使う塗料です。この本では、研磨した凸型の面を仕上げる工程に登場します。',
    contrast: 'サーフェーサーで面を整えることと、離型剤で型から離れやすくすることは別の作業です。',
    source: '26代記録：2026年1月30日〜2月3日 面の仕上げと離型処理',
    sourceUrl: RECORD + '1391736630737633290/1467379294098424011',
  },
  {
    id: 'release-agent',
    term: '離型剤',
    reading: 'りけいざい',
    aliases: [],
    chapter: 'mold',
    short: '固めた材料を型から離しやすくするための材料。',
    description:
      '型と、その上で固める材料が強くくっつくのを防ぐため、型の面に使います。使用する樹脂と組み合わせて選ぶため、製品ごとの塗り方を確認します。',
    contrast: '離型剤は離すための処理で、接着を強くする材料ではありません。',
    source: '一般原理：Fibre Glast 型製作ガイド',
    sourceUrl: MOLD_GUIDE,
  },
  {
    id: 'gelcoat',
    term: 'ゲルコート',
    aliases: ['ゲルコート面'],
    chapter: 'mold',
    short: '型や製品の表面をつくる、樹脂の仕上げ層。',
    description:
      '繊維を重ねる層とは別に、表面をつくるために塗る樹脂の層です。この本では、凸型に塗った面が、取り外した凹型の内側の成形面になります。',
    contrast: 'ゲルコートは表面として残る層で、離型剤とは役割が違います。',
    source: '26代の型工程／一般原理：Fibre Glast 型製作ガイド',
    sourceUrl: MOLD_GUIDE,
  },
  {
    id: 'layup',
    term: '積層',
    reading: 'せきそう',
    aliases: ['積層材'],
    chapter: 'skin',
    short: '薄い材料を、決めた順序と向きで重ねること。',
    description:
      '布状の繊維や木の薄板などを重ね、一つの部品をつくります。この本では、何を何の上に置くかに加え、繊維の向きと、最後に残る材料を読み分けます。',
    contrast: '重ねる積層、樹脂を染み込ませる含浸、固まる硬化は、別々の意味です。',
    source: '26代の外皮工程／一般原理：WEST SYSTEM 積層と真空引き',
    sourceUrl: VACUUM_MATERIALS,
  },
  {
    id: 'impregnation',
    term: '含浸',
    reading: 'がんしん',
    aliases: ['含浸不足'],
    chapter: 'skin',
    short: '布状の繊維のすき間まで、樹脂を行き渡らせること。',
    description:
      '樹脂を表面に載せるだけでなく、繊維の束の中まで染み込ませる作業です。この本では、袋やフィルムで支えながらクロスに樹脂を含ませる記録を読みます。',
    contrast: '含浸しただけでは固まっていません。重ねた後には、指定された硬化の工程が続きます。',
    source: '26代記録：2026年4月26日・29日 クロスの含浸と移送',
    sourceUrl: RECORD + '1391736630737633290/1498259101350756492',
  },
  {
    id: 'cure',
    term: '硬化',
    reading: 'こうか',
    aliases: ['硬化条件'],
    chapter: 'skin',
    short: '樹脂などが化学反応によって固くなること。',
    description:
      'この本のエポキシ系材料では、土台になる材料と、それを固める相手を混ぜることで、中の結び付きが変わって固まります。必要な時間や温度は材料ごとに異なり、触って固いことだけでは完了を決めません。',
    contrast: '水が蒸発する「乾燥」と同じ意味ではありません。',
    source: '一般原理：WEST SYSTEM 樹脂と硬化剤',
    sourceUrl: EPOXY,
  },
  {
    id: 'demolding',
    term: '脱型',
    reading: 'だっけい',
    aliases: [],
    chapter: 'mold',
    short: '型の上や内側で固めた部品を、型から取り外すこと。',
    description:
      '形を保てる状態まで固めた後、型と部品を分ける作業です。この本では、凸型から凹型を外す場面と、凹型から外皮を外す場面の両方に出てきます。',
    contrast: '同じ「脱型」でも、外す物と残す型が工程によって変わります。',
    source: '26代記録：2026年2月6日 凹型の脱型',
    sourceUrl: RECORD + '1391736630737633290/1469290760514834534',
  },
  {
    id: 'skin',
    term: '外皮',
    reading: 'がいひ',
    aliases: [],
    chapter: 'overview',
    short: 'ブレードの外形をつくり、内部を覆う薄い部品。',
    description:
      '完成したプロペラの外側になる部品で、この本では二つの面を別々につくります。それぞれの外皮は、炭素繊維と樹脂で固めた層の間に、薄い木材を挟む構成です。',
    contrast: '外皮は、塗装の膜だけを指す言葉ではありません。',
    source: '26代の外皮工程・構造説明',
  },
  {
    id: 'cloth',
    term: 'クロス',
    aliases: ['カーボンクロス'],
    chapter: 'skin',
    short: '細い繊維を、布のような面に織った材料。',
    description:
      '炭素やガラスなどの繊維を織った布で、樹脂と組み合わせて使います。「カーボンクロス」は炭素繊維の布を指し、布だけの状態と、樹脂で固めた状態を区別して読みます。',
    contrast: '束を長く並べるロービングに対して、クロスは面として扱う布です。',
    source: '一般原理：東レ 炭素繊維織物',
    sourceUrl: 'https://www.cf-composites.toray/products/fabrics/',
  },
  {
    id: 'carbon-fiber',
    term: 'CF',
    reading: 'シーエフ',
    aliases: ['炭素繊維', 'カーボン繊維'],
    chapter: 'skin',
    short: '炭素を主成分とする、補強に使う細い繊維。',
    description:
      'Carbon Fiberの略で、材料を補強する細い繊維のことです。この本では、布状のクロスや長い束として登場し、樹脂と組み合わせて部品をつくります。',
    contrast: 'CFは繊維、CFRPはその繊維と樹脂を組み合わせた材料です。',
    source: '一般原理：Toray Carbon Fiber Terminology',
    sourceUrl: CARBON_TERMS,
  },
  {
    id: 'cfrp',
    term: 'CFRP',
    reading: 'シーエフアールピー',
    aliases: ['炭素繊維強化プラスチック'],
    chapter: 'skin',
    short: '炭素繊維を樹脂と組み合わせて補強した材料。',
    description:
      '炭素繊維が補強を担い、樹脂が繊維をまとめる材料です。この本では、樹脂を含ませたクロスを重ねて固め、外皮などをつくります。',
    contrast: '黒い布そのものではなく、繊維と樹脂の組み合わせを表す名前です。',
    source: '一般原理：Toray Carbon Fiber Terminology',
    sourceUrl: CARBON_TERMS,
  },
  {
    id: 'core',
    term: 'コア',
    aliases: ['バルサコア'],
    chapter: 'skin',
    short: '二枚の表面材の間に挟み、厚みをつくる芯材。',
    description:
      'サンドイッチの具のように、表裏の薄い材料の間へ入れる芯です。この本では軽い木材のバルサを使い、置く位置や継ぎ目の重なりを確認します。',
    contrast: 'コアは部品の中に残ります。硬化後に取り外す副資材とは違います。',
    source: '26代記録：2025年10月22日 外皮コアの練習',
    sourceUrl: RECORD + '1391736630737633290/1430606811676934247',
  },
  {
    id: 'balsa',
    term: 'バルサ',
    aliases: [],
    chapter: 'skin',
    short: '軽い木材で、この本では薄い芯材として使うもの。',
    description:
      '木の種類の名前で、教材の写真では薄い板として登場します。外皮やウェブ材の芯に使いますが、使う場所によって厚みなどの指定が異なります。',
    contrast: 'バルサは材料名、コアはその材料が担う芯の役割を表します。',
    source: '26代記録：2025年10月22日 外皮コアの練習／26代ウェブ工程',
    sourceUrl: RECORD + '1391736630737633290/1430606811676934247',
  },
  {
    id: 'consumables',
    term: '副資材',
    reading: 'ふくしざい',
    aliases: [],
    chapter: 'skin',
    short: '成形を助け、完成した部品には残さない材料。',
    description:
      '材料を押さえる、空気の通り道をつくるなど、製作中の働きを受け持つ材料です。この本では、ピールプライ、ブリーザー、袋などを指し、硬化後に取り外します。',
    contrast: '外皮に残るクロスやコアと、後で外す副資材を別々に並べて考えます。',
    source: '一般原理：WEST SYSTEM 真空成形用材料／26代外皮工程',
    sourceUrl: VACUUM_MATERIALS,
  },
  {
    id: 'peel-ply',
    term: 'ピールプライ',
    aliases: ['ピールプライクロス'],
    chapter: 'skin',
    short: '固めた後に剥がすため、積層材の上へ置く布。',
    description:
      '樹脂を含む層の上に重ね、硬化後に剥がす布です。この本では完成した外皮に残る布ではなく、表面を覆う副資材として読みます。',
    contrast: '見た目が布でも、カーボンクロスと同じように部品へ残す材料ではありません。',
    source: '一般原理：WEST SYSTEM Release fabric',
    sourceUrl: VACUUM_MATERIALS,
  },
  {
    id: 'breather',
    term: 'ブリーザー',
    aliases: ['ブリーザークロス'],
    chapter: 'skin',
    short: '袋の中で、空気が流れる道を保つための布。',
    description:
      '空気を抜くときに、袋の各所からポンプへ空気が流れるようにする材料です。この本ではピールプライの上を覆い、硬化後に取り外します。',
    contrast: '表面から剥がすピールプライと、空気の通り道を保つブリーザーは役割が違います。',
    source: '一般原理：WEST SYSTEM Breather fabric',
    sourceUrl: VACUUM_MATERIALS,
  },
  {
    id: 'bagging',
    term: 'バギング',
    aliases: ['バギング材'],
    chapter: 'skin',
    short: '積層材を袋やフィルムで覆い、空気が漏れないようにすること。',
    description:
      '重ねた材料と副資材を覆い、空気を抜けるよう周囲を密封する作業です。この本では、その後に真空ポンプで袋の内側の空気を抜きます。',
    contrast: '覆って密封する準備がバギング、内側の空気を抜く動作が真空引きです。',
    source: '一般原理：WEST SYSTEM 真空成形用材料',
    sourceUrl: VACUUM_MATERIALS,
  },
  {
    id: 'vacuum',
    term: '真空引き',
    reading: 'しんくうびき',
    aliases: [],
    chapter: 'skin',
    short: '密封した袋の内側から、ポンプで空気を抜くこと。',
    description:
      '袋の内側の圧力を下げると、外側の空気の圧力によって袋が材料へ押し付けられます。この本では積層材を押さえる工程で使い、必要な圧力や時間は使用条件として別に確認します。',
    contrast: '空気を完全にゼロにした、という意味ではありません。',
    source: '一般原理：WEST SYSTEM 真空成形の原理',
    sourceUrl: VACUUM_MATERIALS,
  },
  {
    id: 'flange',
    term: 'フランジ',
    aliases: [],
    chapter: 'flange',
    short: 'この本では、外皮の内側を長く補強する部分。',
    description:
      '26代の工程では、外皮の内側に繊維の束と細い布を重ねてつくる部分を指します。内部の板状部材であるウェブと接するため、その位置を写し取る作業につながります。',
    contrast: '配管などでいう輪状のフランジではなく、このブレード内の補強部分の呼び名です。',
    source: '26代記録：2026年4月24日・5月8日 フランジの位置出し',
    sourceUrl: RECORD + '1391736630737633290/1503209007295500409',
  },
  {
    id: 'roving',
    term: 'ロービング',
    aliases: ['ロービング束'],
    chapter: 'flange',
    short: '多くの細い繊維を、同じ向きにそろえた長い束。',
    description:
      '繊維を布へ織る前のような、長く続く束です。この本では外皮の内側へ根元から先端に向けて並べ、フランジをつくります。',
    contrast: '一本という数え方だけでは太さは決まらないため、使う束の規格も確かめます。',
    source: '一般原理：Toray Carbon Fiber Terminology／26代フランジ記録',
    sourceUrl: CARBON_TERMS,
  },
  {
    id: 'black-belt',
    term: '黒帯',
    reading: 'くろおび',
    aliases: [],
    chapter: 'flange',
    short: 'ロービングの上へ重ねる、細い炭素繊維の布の呼び名。',
    description:
      'この本では、繊維の束を薄く広げて織った、幅の狭いカーボンクロスを指します。ロービングを置いた上に重ねる材料として登場します。',
    contrast: 'ウェブ全体を巻いて包む帯、という意味ではありません。',
    source: '26代工程説明：フランジの黒帯',
  },
  {
    id: 'jig',
    term: '治具',
    reading: 'じぐ',
    aliases: ['受け治具', 'ウェブ立て治具', '貼り合わせ治具'],
    chapter: 'web',
    short: '作業中の部品の位置や向きを保つための道具。',
    description:
      '部品を支えたり、決めた位置へ置けるようにしたりする道具です。この本では、外皮を下から支える物、ウェブを立てる物、二つの外皮を押さえる物を使い分けます。',
    contrast: '治具は製作を助ける道具で、完成したブレードの内部に残す部品ではありません。',
    source: '26代記録：2026年3月25日・28日 ウェブ取付け',
    sourceUrl: RECORD + '1391736630737633290/1486353560617746522',
  },
  {
    id: 'spar',
    term: '桁',
    reading: 'けた',
    aliases: [],
    chapter: 'web',
    short: '翼などの長い構造を内側から支える、骨組みの一つ。',
    description:
      '翼の根元から先端へ向かう方向に配置される、主な骨組みを指す一般的な言葉です。この本では、根元側に取り付ける「ペラスパー」と、その固定に使う「桁リブ」を見分けます。',
    contrast: '桁は役割を含む一般名で、この本に出てくる個々の部品名とは分けて読みます。',
    source: '26代工程説明：ペラスパーと桁リブをもとに一般語を補足',
  },
  {
    id: 'propeller-spar',
    term: 'ペラスパー',
    aliases: ['スパー'],
    chapter: 'web',
    short: 'この本で、ブレードの根元側に取り付ける骨組みの呼び名。',
    description:
      '26代の内部部材の一つで、外皮の根元側へ取り付けます。桁リブと組み合わせて位置を保つため、本文では単体の形と、取り付け先の両方を確認します。',
    contrast: 'ウェブと同じ部品ではなく、別の名前と取付け位置を持つ内部部材です。',
    source: '26代記録：2026年3月24日 スパーと治具',
    sourceUrl: RECORD + '1391736630737633290/1485941973356384379',
  },
  {
    id: 'spar-rib',
    term: '桁リブ',
    reading: 'けたりぶ',
    aliases: [],
    chapter: 'web',
    short: 'この本で、ペラスパーを外皮へ固定するための部品。',
    description:
      '内部の骨組みと外皮をつなぐため、指定された位置に取り付ける部品です。断面のような形に見えても、型をつくるための断面板とは役割が異なります。',
    contrast: '桁リブは完成品の内部に残り、型の断面板や作業用の治具は残しません。',
    source: '26代工程説明：ペラスパーと桁リブの固定',
  },
  {
    id: 'web',
    term: 'ウェブ',
    aliases: ['ウェブ材'],
    chapter: 'web',
    short: '二つの外皮の間へ立て、内側をつなぐ板状の部材。',
    description:
      'この本では、木の芯の両面にガラス繊維の布を重ねた板状の部品です。片側の外皮の内側へ立て、もう片側の外皮にも接する位置と向きに合わせます。',
    contrast: 'インターネットのWebではなく、構造の内部部材を指す言葉です。',
    source: '26代記録：2026年3月19日・23日 ウェブ材製作',
    sourceUrl: RECORD + '1391736630737633290/1485933354640474164',
  },
  {
    id: 'leading-edge',
    term: '前縁',
    reading: 'ぜんえん',
    aliases: [],
    chapter: 'overview',
    short: '翼の断面で、流れに対して前側となる縁。',
    description:
      '翼の断面の前側にある縁を指します。この本では接着する場所を区別する名前にもなり、写真の左右だけで決めず、図と向きを照合します。',
    contrast: '前縁と後縁は部品の名前です。画面を回転しても名前は入れ替わりません。',
    source: '一般原理：NASA Wing Geometry／26代貼り合わせ工程',
    sourceUrl: WING_GEOMETRY,
  },
  {
    id: 'trailing-edge',
    term: '後縁',
    reading: 'こうえん',
    aliases: [],
    chapter: 'overview',
    short: '翼の断面で、流れに対して後ろ側となる縁。',
    description:
      '翼の断面の後ろ側にある縁を指します。この本では、前縁とは接着のしかたが異なる場所として扱うため、二つを別々に指せるようにします。',
    contrast: '写真の手前側や奥側という意味ではありません。',
    source: '一般原理：NASA Wing Geometry／26代貼り合わせ工程',
    sourceUrl: WING_GEOMETRY,
  },
  {
    id: 'lengthwise',
    term: '長手方向',
    reading: 'ながてほうこう',
    aliases: [],
    chapter: 'overview',
    short: 'この本では、ブレードの根元から先端へ向かう方向。',
    description:
      '長い物の、長さに沿った方向です。プロペラの布の向きや補強材の置き方を読むときは、まず根元と先端を見つけ、その間の方向を基準にします。',
    contrast: '前縁から後縁へ横切る方向とは違います。',
    source: '26代工程説明：外皮の繊維方向・ロービング配置',
  },
  {
    id: 'chord',
    term: '翼弦',
    reading: 'よくげん',
    aliases: ['翼弦方向', '翼弦線'],
    chapter: 'overview',
    short: '翼の断面で、前縁と後縁を結ぶまっすぐな線。',
    description:
      '断面の前側の縁から後ろ側の縁へ引く直線です。形や方向を説明するための基準で、曲がった表面をなぞった線とは区別します。',
    contrast: '根元から先端へ向かう長手方向ではなく、断面を横切る方向を示します。',
    source: '一般原理：NASA Wing Geometry',
    sourceUrl: WING_GEOMETRY,
  },
  {
    id: 'upper',
    term: 'upper',
    reading: 'アッパー',
    aliases: ['Upper', 'UPPER'],
    chapter: 'overview',
    short: 'この本で、内部部材を先に取り付ける側の外皮の名前。',
    description:
      '26代の記録で二つの外皮を区別する呼び名の一つです。組立てでは、upperを治具に載せて内部部材を固定し、その上へunderをかぶせます。',
    contrast: '英単語の「上」から、作業台上でも常に上側にあると考えないでください。',
    source: '26代工程説明：内部部材の取付け・貼り合わせ',
  },
  {
    id: 'under',
    term: 'under',
    reading: 'アンダー',
    aliases: ['Under', 'UNDER'],
    chapter: 'overview',
    short: 'この本で、内部部材を付けたupperへかぶせる側の外皮。',
    description:
      '26代の記録で、upperと対になる外皮の呼び名です。貼り合わせでは、内部部材との接触を確かめてから、upperへかぶせます。',
    contrast: '名前の「下」と、組立て中に上から下ろす動作を混同しないようにします。',
    source: '26代工程説明：貼り合わせ',
  },
  {
    id: 'dry-fit',
    term: '仮合わせ',
    reading: 'かりあわせ',
    aliases: [],
    chapter: 'join',
    short: '本接着の前に部品を合わせ、位置や接触を確かめること。',
    description:
      'まだ接着を確定させずに部品を置き、互いに合うかを調べます。この本では、二つの外皮や内部部材の位置を、接着材を混ぜる前に確認する場面です。',
    contrast: '仮合わせで合ったことと、本接着が完了したことは別です。',
    source: '26代記録：2026年5月28日 貼り合わせの準備',
    sourceUrl: RECORD + '1391744408918949968/1509340539403767840',
  },
  {
    id: 'overlap',
    term: '重ね代',
    reading: 'かさねしろ',
    aliases: [],
    chapter: 'join',
    short: '二つの材料を重ねてつなぐため、あらかじめ残す部分。',
    description:
      '部品の端をぴったり突き合わせるのではなく、一方を他方へ重ねられるように残す範囲です。この本では前縁で外皮同士を接着する部分として登場します。',
    contrast: '余っていて切り落とす部分ではなく、接着に必要な部分です。',
    source: '26代工程説明：外皮コアと前縁の貼り合わせ',
  },
  {
    id: 'epoxy',
    term: 'エポキシ樹脂',
    aliases: ['エポキシ'],
    chapter: 'skin',
    short: '繊維をまとめたり部品を接着したりする、樹脂の一種。',
    description:
      '固まると部品の一部として残り、繊維をまとめたり部品同士を接着したりする材料です。この本では、固まる反応を起こす相手である「硬化剤」と混ぜて使います。染み込ませる用途と接着する用途があるため、使用製品と条件をその都度確かめます。',
    contrast: 'どの硬化剤でも使えるわけではなく、混合比も製品ごとに決まります。',
    source: '一般原理：WEST SYSTEM 樹脂と硬化剤',
    sourceUrl: EPOXY,
  },
  {
    id: 'epoxy-putty',
    term: 'エポパテ',
    aliases: ['エポキシパテ'],
    chapter: 'join',
    short: 'エポキシ系の材料を、盛って使える状態にしたパテ。',
    description:
      '液体の樹脂より形を保ちやすく、隙間などへ盛る用途で使う材料です。この本の貼り合わせでは、ウェブ上部と後縁に使う記録があり、配合や量は記録だけで一律に決めません。',
    contrast: '前縁へ塗る樹脂と、ウェブ上部・後縁へ盛るエポパテを取り違えないようにします。',
    source: '26代記録：2026年5月30日・6月2日 貼り合わせ用エポパテ',
    sourceUrl: RECORD + '1391736630737633290/1510981510063460362',
  },
  {
    id: 'masking',
    term: 'マスキング',
    aliases: ['マスキングテープ'],
    chapter: 'finish',
    short: '塗料などを付けたくない場所を、テープやシートで覆うこと。',
    description:
      '必要な場所だけに塗料などを付けるため、残したい部分を覆う作業です。この本の仕上げでは、図案に沿って切ったシートを移し、塗る境界をつくります。',
    contrast: '記録にはテープで一時固定する場面もあります。テープを使う目的は場面ごとに読みます。',
    source: '26代記録：2026年7月17日 マスキングの移送',
    sourceUrl: RECORD + '1391736630737633290/1528355660578685039',
  },
  {
    id: 'styro',
    term: 'スタイロ',
    aliases: ['スタイロフォーム'],
    chapter: 'mold',
    short: 'この記録で、型の下地に使う硬い発泡プラスチック板の呼び名。',
    description:
      '教材写真にある、断面板の間を埋める青い軽量の板材です。この本では、上にパテを盛る余地を残して入れる下地として扱います。',
    contrast: 'スタイロの表面そのものが、完成させる型の面ではありません。',
    source: '26代記録：2025年12月1日 本番型の下地',
    sourceUrl: RECORD + '1391736630737633290/1445269288368869376',
  },
  {
    id: 'taper',
    term: 'テーパー',
    aliases: ['テーパーさせる'],
    chapter: 'skin',
    short: '端へ向かうにつれて、厚みや幅を少しずつ小さくした形。',
    description:
      '急な段差をつくらず、徐々に細くしたり薄くしたりする形です。この本のコアでは、前縁の端へ向かって木の厚みを薄くすることを指します。',
    contrast: '端をただ短く切ることと、厚みを徐々に薄くすることは別です。',
    source: '26代工程説明：前縁のコアと重ね代',
  },
  {
    id: 'gfrp',
    term: 'GFRP',
    reading: 'ジーエフアールピー',
    aliases: ['ガラス繊維強化プラスチック'],
    chapter: 'mold',
    short: 'ガラスの繊維を樹脂と組み合わせて補強した材料。',
    description:
      '細いガラス繊維を樹脂でまとめてつくる材料です。この本では型の積層などに登場し、炭素繊維を使うCFRPとは材料名を分けて読みます。',
    contrast: '窓ガラスの板をそのまま重ねるわけではありません。',
    source: '一般原理：FAA 複合材構造／26代の型工程',
    sourceUrl:
      'https://www.faa.gov/airports/resources/advisory_circulars/index.cfm/go/document.information/documentNumber/20-107B',
  },
  {
    id: 'glass-cloth',
    term: 'ガラスクロス',
    aliases: [],
    chapter: 'web',
    short: '細いガラス繊維を、布のような面に織った材料。',
    description:
      'ガラスを細い繊維にして織った布で、樹脂と組み合わせて使います。この本のウェブでは、薄いガラスクロスを木の芯の両面に重ねます。',
    contrast: '「マイクロガラスクロス」という名前だけで製品の厚さや繊維の向きは決められません。',
    source: '26代工程説明：ウェブ材のサンドイッチ構成',
  },
  {
    id: 'glass-mat',
    term: 'ガラスマット',
    aliases: [],
    chapter: 'mold',
    short: '短いガラス繊維などを、面状にまとめた材料。',
    description:
      'ガラス繊維を織らずに、シートのようにまとめた材料です。この本では凹型をつくる積層に登場するため、クロスとは別の材料として順序を確認します。',
    contrast: '縦横に織り目のあるガラスクロスと、同じ構造ではありません。',
    source: '26代の型工程／一般原理：Fibre Glast 型製作ガイド',
    sourceUrl: MOLD_GUIDE,
  },
  {
    id: 'sandwich',
    term: 'サンドイッチ構造',
    aliases: ['サンドイッチ材', 'サンドイッチ'],
    chapter: 'skin',
    short: '二枚の表面材で、軽い芯材を挟んだ構造。',
    description:
      '表・芯・裏を組み合わせた構造で、この本では繊維と樹脂の層の間にバルサを挟みます。単に三枚を置くだけでなく、互いに接着された一つの部品としてつくります。',
    contrast:
      '外皮の芯と、完成したブレード内部の空間は別です。外皮そのものがサンドイッチになっています。',
    source: '26代の外皮・ウェブ工程',
  },
  {
    id: 'fiber-direction',
    term: '繊維方向',
    reading: 'せんいほうこう',
    aliases: ['繊維の向き', '±45°'],
    chapter: 'skin',
    short: '布や束の中で、細い繊維が延びている方向。',
    description:
      '布の端の向きだけでなく、実際の繊維が走る方向を指します。この本の「±45°」は、根元から先端へ向かう方向に対して、左右へ45度傾く二つの向きです。',
    contrast: '写真の水平線や袋の端を、角度の基準にしないようにします。',
    source: '26代工程説明：外皮・ウェブの繊維方向',
  },
  {
    id: 'radial-position',
    term: 'r',
    reading: 'アール',
    aliases: ['位置を表す r', '半径位置 r', 'r='],
    chapter: 'web',
    short: 'この本の部品位置に付く記号で、測る基準点の確認が必要。',
    description:
      '一般には半径を表す記号ですが、手元の26代工程説明だけでは、現物のどこを測定の始点にするかまで確定できません。「r=」の数値を使う前に、対応する図面の基準点と測る方向を確認します。',
    contrast:
      '部品の端から測った距離や、回転中心からの距離だと自己判断で置き換えないようにします。',
    source: '26代工程説明：ペラスパーと桁リブの位置表記。測定基準は未確認',
  },
  {
    id: 'mdf',
    term: 'MDF',
    reading: 'エムディーエフ',
    aliases: [],
    chapter: 'mold',
    short: '木を細かな繊維にして、接着して板にした材料。',
    description:
      '木の繊維を固めてつくる板材です。この本では練習型の説明に登場し、本番型のステンレス板とは材料が違うことを示す名前として読みます。',
    contrast: '練習型のMDFの条件を、そのまま本番型へ当てはめることはできません。',
    source: '26代記録：2025年9月25日 MDF練習型をもとに一般語を補足',
    sourceUrl: RECORD + '1391736924246376448/1420786120567816202',
  },
  {
    id: 'molding-surface',
    term: '製品面',
    reading: 'せいひんめん',
    aliases: ['成形面'],
    chapter: 'mold',
    short: 'この本で、つくる部品へ形を写すための型の面。',
    description:
      '型のうち、部品の形を直接決める面を指します。型を支える足や側面とは役割が違うため、研磨や積層の写真では、その境界を見分けます。',
    contrast: '型に見えている面すべてが、完成した外皮の表面になるわけではありません。',
    source: '26代記録：2025年9月25日 製品面と周辺の区分',
    sourceUrl: RECORD + '1391736924246376448/1420786120567816202',
  },
  {
    id: 'working-time',
    term: '作業可能時間',
    reading: 'さぎょうかのうじかん',
    aliases: ['可使時間', 'ポットライフ'],
    chapter: 'skin',
    short: '混ぜた材料を、意図した作業に使える時間の目安。',
    description:
      '樹脂などを混ぜてから、塗る、染み込ませるなどの作業ができる時間を指します。容器内での測定条件を表すポットライフと、薄く広げた現場の作業時間は一致するとは限りません。',
    contrast: '作業できる時間と、十分に固まって次工程へ進めるまでの時間は別です。',
    source: '一般原理：WEST SYSTEM User Manual の時間区分',
    sourceUrl: 'https://www.westsystem.com/app/uploads/2022/10/User-Manual-2015.pdf',
  },
  {
    id: 'tip',
    term: 'ペラ端',
    reading: 'ぺらたん',
    aliases: [],
    chapter: 'finish',
    short: 'この本で、ブレードの先端に取り付ける部品の呼び名。',
    description:
      '長いブレードの先端側の形をつくるため、最後の工程で取り付ける部品です。この本では、仮止めして位置を見る段階と、本接着する段階を分けます。',
    contrast: 'ブレード全体を指す名前ではなく、その先端側の部品名です。',
    source: '26代記録：2026年6月26日・27日 ペラ端の取付け',
    sourceUrl: RECORD + '1391736630737633290/1520030732591038486',
  },
  {
    id: 'blade',
    term: 'ブレード',
    aliases: ['羽根'],
    chapter: 'overview',
    short: 'プロペラを構成する、長く伸びた羽根の一本。',
    description:
      '回転するプロペラの、根元から先端へ伸びる羽根を指します。この本は、二つの外皮と内部部材を組み合わせて、その一本をつくる流れを追います。',
    contrast: '外皮はブレードを構成する部品で、ブレード全体と同じ意味ではありません。',
    source: '26代の構造・貼り合わせ工程',
  },
  {
    id: 'offset',
    term: 'オフセット',
    aliases: [],
    chapter: 'mold',
    short: 'ある基準から、決められた距離だけ位置をずらすこと。',
    description:
      '元の線や面を基準に、必要な分だけ離した位置をつくることです。この本の型ではパテを盛る厚みを残して下地を低くする意味で使いますが、フランジの位置出しでは別の位置関係を指します。',
    contrast:
      'いつでも下げるという意味ではありません。何から、どちらへ、どれだけずらすかを組にして読みます。',
    source: '26代の型工程／2026年3月23日 フランジの位置ずれ記録',
    sourceUrl: RECORD + '1391736630737633290/1485933501076340826',
  },
  {
    id: 'fair-surface',
    term: '面を出す',
    reading: 'めんをだす',
    aliases: ['面出し'],
    chapter: 'mold',
    short: '凸凹を整えて、基準に沿ったつながる面をつくること。',
    description:
      '盛ったパテなどを削り、隣り合う場所が段差やうねりなくつながるように整える作業の言い方です。この本では、断面板が示す形を残しながら、その間の面を整えます。',
    contrast: '必ず平らな板状にする意味ではありません。型の曲面を整える場合にも使います。',
    source: '26代記録：2025年9月25日 練習型の面の整え方',
    sourceUrl: RECORD + '1391736924246376448/1420786120567816202',
  },
  {
    id: 'airfoil-thickness',
    term: '翼厚',
    reading: 'よくあつ',
    aliases: [],
    chapter: 'flange',
    short: '翼の断面で、表側と裏側の間にある厚み。',
    description:
      '翼の断面の二つの表面の間隔を表す言葉です。この本では、断面のどのあたりが厚いかを見て、内部部材の位置関係を読むために使います。',
    contrast: '外皮をつくる材料そのものの厚さではなく、翼全体の断面の厚みです。',
    source: '一般原理：NASA FoilSim Thickness Definition',
    sourceUrl: 'https://www.grc.nasa.gov/WWW/k-12/FoilSim/Manual/fsim0027.htm',
  },
  {
    id: 'maximum-thickness',
    term: '最大翼厚',
    reading: 'さいだいよくあつ',
    aliases: [],
    chapter: 'flange',
    short: '翼のある断面で、表と裏の間隔が最も大きい厚み。',
    description:
      '前縁から後縁へ断面を見たとき、最も厚くなる部分の厚みです。この本の「最大翼厚付近」は位置の概略を伝える表現で、フランジを置く線は治具や図面から確かめます。',
    contrast: '幅の中央や、写真で最もふくらんで見える位置と必ず一致するわけではありません。',
    source: '一般原理：NASA FoilSim／26代フランジの位置出し',
    sourceUrl: 'https://www.grc.nasa.gov/WWW/k-12/FoilSim/Manual/fsim0027.htm',
  },
  {
    id: 'micro-glass-cloth',
    term: 'マイクロガラスクロス',
    aliases: [],
    chapter: 'web',
    short: 'この本で、ウェブの木の芯の両面へ重ねる薄いガラス繊維の布。',
    description:
      '細いガラス繊維でできた薄い布の呼び名です。26代のウェブ材では、バルサの両面へ重ねる材料として出てきます。',
    contrast:
      '「マイクロ」という呼び名だけで厚さなどは決まらないため、使用製品の規格も確かめます。',
    source: '26代工程説明：ウェブ材の構成',
  },
  {
    id: 'shell-closing',
    term: 'ペラ被せ',
    reading: 'ぺらかぶせ',
    aliases: ['ペラかぶせ'],
    chapter: 'join',
    short: '二つの外皮を合わせ、一つのブレードに閉じる作業の呼び名。',
    description:
      '26代の作業記録で、upperにunderをかぶせて貼り合わせる工程を指す呼び名です。部品の中が見えなくなる前に、内部部材の位置や接着する場所を確かめます。',
    contrast: 'かぶせた外見だけでは、内側の接着や硬化が完了したとは判断できません。',
    source: '26代の貼り合わせ工程・記録の呼称',
  },
  {
    id: 'degreasing',
    term: '脱脂',
    reading: 'だっし',
    aliases: [],
    chapter: 'join',
    short: '接着や塗装の妨げになる、表面の油分を取り除くこと。',
    description:
      '表面に残った油や脂などを取り除く作業です。使える洗浄方法は材料によって違うため、この本の用語説明を特定の洗浄液や拭き方の指定としては扱いません。',
    contrast: '油分を除く脱脂、粉を除く清掃、表面を削る研磨は、同じ作業ではありません。',
    source: '一般原理：WEST SYSTEM Surface Preparation',
    sourceUrl: 'https://www.westsystem.com/instruction/epoxy-basics/surface-preparation/',
  },
  {
    id: 'resin',
    term: '樹脂',
    reading: 'じゅし',
    aliases: [],
    chapter: 'skin',
    short: 'この本では、固めて部品の一部にするプラスチック系の材料。',
    description:
      'この本では、布へ染み込ませたり、部品へ塗ったりした後に固める材料を指します。固まった材料は、繊維をまとめたり、部品同士をつないだりする部分として残ります。エポキシは、この樹脂の種類の一つです。',
    contrast: '水のように蒸発してなくなる液体として扱うものではありません。',
    source: '一般原理：WEST SYSTEM 樹脂と硬化剤／26代の外皮工程',
    sourceUrl: EPOXY,
  },
  {
    id: 'base-resin',
    term: '主剤',
    reading: 'しゅざい',
    aliases: [],
    chapter: 'skin',
    short: '二つの材料を混ぜて使う製品で、土台になる側の材料。',
    description:
      'この本のエポキシ系材料では、部品をつくる土台になる樹脂の側を指します。主剤だけで使うのではなく、固まる反応を起こす相手の硬化剤と、指定された比率で混ぜます。',
    contrast:
      '「主剤のほうを多めに入れればよい」という意味ではありません。混ぜる量は製品の指定によります。',
    source: '一般原理：WEST SYSTEM 樹脂と硬化剤',
    sourceUrl: EPOXY,
  },
  {
    id: 'hardener',
    term: '硬化剤',
    reading: 'こうかざい',
    aliases: [],
    chapter: 'skin',
    short: '樹脂と混ぜて、固まる反応を起こす相手となる材料。',
    description:
      'この本のエポキシ系材料では、土台となる材料と一緒に反応して固まるための相手です。対応する製品を、指定された量と組み合わせて使います。',
    contrast: '早く固めるために好きなだけ足す材料ではありません。',
    source: '一般原理：WEST SYSTEM 樹脂と硬化剤',
    sourceUrl: EPOXY,
  },
  {
    id: 'chemlease',
    term: 'ケムリース',
    aliases: ['Chemlease'],
    chapter: 'mold',
    short: '本書の型の記録に登場する離型剤の製品名。',
    description:
      '固めた部品を型から分けやすくするため、材料を重ねる前に型へ塗る薬剤の名称です。2026年2月3日の記録では研磨の後に塗っています。ここでの呼び名だけでは製品番号を特定できないため、塗り方や回数は対象製品の仕様と照合します。',
    contrast:
      '表面の下地を整えるサーフェーサーや、型の表面として残るゲルコートとは用途が違います。',
    source: '26代記録：2026年2月3日 型の仕上げと離型処理',
  },
  {
    id: 'core-joint',
    term: 'コアの継ぎ目',
    reading: 'こあのつぎめ',
    aliases: ['コア相貫部', 'コア材相貫部', '相貫部'],
    chapter: 'skin',
    short: '芯に使う板どうしの端が出会い、つながる場所。',
    description:
      '26代の日記では、コア材の端をつなぐ部分を「相貫部」と呼んでいます。2026年2月24日にこの場所の凹凸が記録され、4月7日には接ぎ方が話題になっています。この語だけから端の加工形状や寸法は決めず、対象の図面で確かめます。',
    contrast: '片方が上へ乗る重なりと、端を突き合わせる継ぎ方を写真で区別します。',
    source: '26代記録：2026年2月24日・4月7日 コア材',
  },
];
